### 1. Load Library

In [1]:
import numpy as np
import pandas as pd

### 2. Load Data

In [14]:
df = pd.DataFrame({"pendapatan": [3, 4, 5, 4, 6, 5, 4, 50, 4]})

### 3.1 Interquartile Range (IQR)

In [15]:
Q1 = df["pendapatan"].quantile(0.25)
Q3 = df["pendapatan"].quantile(0.75)
IQR = Q3 - Q1
batas_bawah = Q1 - 1.5 * IQR
batas_atas = Q3 + 1.5 * IQR

### 3.1.1 Deteksi

In [16]:
outliers_iqr = df[
    (df["pendapatan"] < batas_bawah) | (df["pendapatan"] > batas_atas)
]
outliers_iqr

   pendapatan
7          50

### 3.1.2. Clipping (memotong ke batas terdekat)

In [17]:
df["pendapatan_clipped"] = df["pendapatan"].clip(
    lower=batas_bawah, upper=batas_atas
)
df

   pendapatan  pendapatan_clipped
0           3                 3.0
1           4                 4.0
2           5                 5.0
3           4                 4.0
4           6                 6.0
5           5                 5.0
6           4                 4.0
7          50                 6.5
8           4                 4.0