### 1. Load Library

In [1]:
import pandas as pd

### 2. Load Dataset

In [2]:
data = {
    "kota": [
        " Jakarta ",
        "jkt",
        "JAKARTA",
        "Bandung",
        "Bandung",
        "  surabaya  ",
    ],
    "kategori": [
        "Elektronik",
        "elektronik",
        "ELEKTRONIK",
        "Pakaian",
        "Pakaian",
        "makanan",
    ],
}
df = pd.DataFrame(data)
df

           kota    kategori
0      Jakarta   Elektronik
1           jkt  elektronik
2       JAKARTA  ELEKTRONIK
3       Bandung     Pakaian
4       Bandung     Pakaian
5    surabaya       makanan

### 3. Standardisasi Huruf (Lowercasing) & Pembersihan Spasi

In [3]:
kolom_teks = ["kota", "kategori"]
for col in kolom_teks:
    df[col] = (
        df[col]
        .str.lower() #ubah semua huruf jadi kecil
        .str.strip() #hapus spasi di awal dan akhir string
        .str.replace(r"\s+", " ", regex=True) #ubah spasi ganda di tengah jadi 1 spasi
    )
df

       kota    kategori
0   jakarta  elektronik
1       jkt  elektronik
2   jakarta  elektronik
3   bandung     pakaian
4   bandung     pakaian
5  surabaya     makanan

### 4. Ketidakkonsistenan Pengetikan / Singkatan

In [7]:
kamus_koreksi = {
    "jkt": "jakarta",
    "bdg": "bandung",
    "sby": "surabaya",
}
df["kota"] = df["kota"].replace(kamus_koreksi)
df

       kota    kategori
0   jakarta  elektronik
1   jakarta  elektronik
2   jakarta  elektronik
3   bandung     pakaian
4   bandung     pakaian
5  surabaya     makanan

### 5. Penghapusan Duplikasi

In [8]:
df_clean = df.drop_duplicates().reset_index(drop=True)
df_clean

       kota    kategori
0   jakarta  elektronik
1   bandung     pakaian
2  surabaya     makanan